// eslint-disable-next-line canonical/filename-match-exported,import/no-unassigned-import
import "./globals.css";
import { type Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Pokemon",
};

const RootLayout = ({ children }: { readonly children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={`overflow-hidden ${inter.className}`}>{children}</body>
    </html>
  );
};

export default RootLayout;
